dell/csi-baremetal

pkg/scheduler/patcher/openshift_patcher.sh

Add uninstallation of scheduler for OpenShift
https://github.com/dell/csi-baremetal/issues/97

Add ability to uninstall scheduler extender on OpenShift

---

charts/scheduler/values.yaml
docs/CONTRIBUTING.md
docs/PULL_REQUEST_TEMPLATE.md
docs/README.md

[ISSUE-93](https://github.com/dell/csi-baremetal/issues/93) Update readme and contributing docs to make them up-to-date.
Not relevant for documentation

[ISSUE-93] update documentation

---

test/e2e/common/util.go

This change will speed up e2e testing
Add support for parallel PODs removal in e2e tests cleanup logic.

[ISSUE-110] Remove pods in e2e tests in parallel to speed up tests

---

charts/baremetal-csi-plugin/Chart.yaml
charts/scheduler-extender/Chart.yaml
charts/scheduler/Chart.yaml
pkg/base/constants.go
variables.mk

Switch plugin version to 0.0.10 https://github.com/dell/csi-baremetal/issues/112

[ISSUE-112] switch version to 0.0.10

---

docs/proposals/TEMPLATE.md
docs/proposals/node_replacement.md

Add proposal for handling node replacement service procedure. https://github.com/dell/csi-baremetal/issues/98

[ISSUE-98] add NR proposal

---

test/e2e/scenarios/bare-metal-testdriver.go
test/e2e/scenarios/controller-node-fail.go
test/e2e/scenarios/different-sc-test.go
test/e2e/scenarios/drive-health-change.go
test/e2e/scenarios/node-reboot.go
test/e2e/scenarios/scheduler-test.go
test/e2e/scenarios/stress-test.go

Signed-off-by: Yury Kulazhenkov <yury.kulazhenkov@emc.com>
Fix for https://github.com/dell/csi-baremetal/issues/119

[ISSUE-119] e2e from k8s suites should wait for CSI driver boot up

---

charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_csibmnodes.yaml
charts/baremetal-csi-plugin/templates/baremetal-csi-controller.yaml
charts/baremetal-csi-plugin/templates/baremetal-csi-node.yaml
charts/baremetal-csi-plugin/values.yaml

[ISSUE-129](https://github.com/dell/csi-baremetal/issues/129) Ability to deploy CSI on subset of nodes
How to label nodes:
`kubectl label node kind-worker <key>=<value>`
How to deploy CSI:
`helm install csi-baremetal charts/baremetal-csi-plugin --set nodeSelector.key=<key> --set nodeSelector.value=<value>`
Example:
```
$ kubectl get nodes
NAME                 STATUS   ROLES    AGE   VERSION
kind-control-plane   Ready    master   12d   v1.18.2
kind-worker          Ready    <none>   12d   v1.18.2
kind-worker2         Ready    <none>   12d   v1.18.2
kind-worker3         Ready    <none>   12d   v1.18.2
kind-worker4         Ready    <none>   12d   v1.18.2
kind-worker5         Ready    <none>   12d   v1.18.2
kind-worker6         Ready    <none>   12d   v1.18.2
$ kubectl get nodes -l app=csi …
```

[ISSUE-129] Ability to deploy CSI to labeled nodes

---

docs/README.md

Fix typo in installation command in README.md

---

api/v1/acreservationcrd/availablecapacityreservation_types.go
api/v1/availablecapacitycrd/availablecapacity_types.go
api/v1/csibmnodecrd/csibmnode_types.go
api/v1/drivecrd/drive_types.go
api/v1/lvgcrd/lvg_types.go
api/v1/volumecrd/volume_types.go
charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_availablecapacities.yaml
charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_availablecapacityreservations.yaml
charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_csibmnodes.yaml
charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_drives.yaml
charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_lvgs.yaml
charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_volumes.yaml
cmd/node/main.go
pkg/base/k8s/fake_kubeclient.go
pkg/base/k8s/kubeclient.go
pkg/base/k8s/kubeclient_test.go
test/e2e/common/types.go
test/e2e/scenarios/bare-metal-testdriver.go
test/e2e/scenarios/drive-health-change.go
test/e2e/scenarios/scheduler-test.go

Implements https://github.com/dell/csi-baremetal/issues/132

[ISSUE-132] Change scope for CRs from Namespaced to Cluster

---

pkg/base/capacityplanner/helpers.go
pkg/base/capacityplanner/helpers_test.go
pkg/common/volume_operations.go

Fix for: https://github.com/dell/csi-baremetal/issues/139

[ISSUE-139] Fix ReservationHelper.ReleaseReservation method to remove right ACR

---

pkg/base/capacityplanner/helpers.go
pkg/base/capacityplanner/helpers_test.go
pkg/base/capacityplanner/planner.go
pkg/base/capacityplanner/planner_test.go

Fixes https://github.com/dell/csi-baremetal/issues/141

[ISSUE-141] Replace capacityplanner.choseACinACRWithLessAC function with choseACFromOldestACR

---

docs/README.md

[ISSUE-136] Fix typo in installation command in README.md

---

Makefile.docker

[Issue 137](https://github.com/dell/csi-baremetal/issues/137)
Use --location flag for curl operations

[ISSUE-137] change curl flags

---

charts/baremetal-csi-plugin/Chart.yaml
charts/csibm-operator/Chart.yaml
charts/scheduler-extender/Chart.yaml
charts/scheduler/Chart.yaml
pkg/base/constants.go
variables.mk

[ISSUE-155](https://github.com/dell/csi-baremetal/issues/155) CSI version to 0.0.11
N/A

[ISSUE-155] update version to 0.0.11

---

api/v1/constants.go
api/v1/types.proto
charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_drives.yaml
pkg/node/volumemgr.go

https://github.com/dell/csi-baremetal/issues/159
Added operational status field in Drive CRD spec.

[ISSUE-159] added op status for drive crd

---

pkg/base/k8s/kubeclient.go

issue: https://github.com/dell/csi-baremetal/issues/166
Fix bug in a k8s_client.  

[ISSUE-166] Fix k8s client

---

Makefile.validation

https://github.com/dell/csi-baremetal/issues/168
fix typo in lint-charts make target

[ISSUE-168] fix typo

---

charts/baremetal-csi-plugin/templates/baremetal-csi-node.yaml
charts/baremetal-csi-plugin/values.yaml
pkg/events/events.go
pkg/events/events_test.go

* Add new value in helm chart to deploy CSI with event config
* Change structure `Options` to support yaml in ConfigMap
Solves https://github.com/dell/csi-baremetal/issues/181

[Issue-181] Add support for event config 

---

pkg/node/volumemgr.go
pkg/node/volumemgr_test.go

[Issue-195] Available capacity CR is removed when volume provisioned

---

pkg/crcontrollers/drive/drivecontroller.go
pkg/node/volumemgr.go

[ISSUE-200] Remove drive DR when disk replacement completed successfully

---

api/v1/constants.go
pkg/base/k8s/cr_helper.go
pkg/base/k8s/cr_helper_test.go
pkg/crcontrollers/drive/drivecontroller.go
pkg/node/volumemgr.go

Add support for drive replacement for LVG volumes

[ISSUE-204] Add LVG support to DR procedure

---

pkg/base/linuxutils/lvm/lvm.go
pkg/node/volumemgr.go

https://github.com/dell/csi-baremetal/issues/207
If Drive CRs exist, search system drive UUID among them.

[ISSUE-207] detect system drive after restart

---

pkg/crcontrollers/drive/drivecontroller.go
pkg/eventing/eventing.go
pkg/node/volumemgr.go
pkg/node/volumemgr_test.go

Change info type to normal type in events

[Issue-220] Change info type to normal type

---

charts/baremetal-csi-plugin/templates/baremetal-csi-controller.yaml
charts/baremetal-csi-plugin/templates/baremetal-csi-node.yaml
charts/baremetal-csi-plugin/values.yaml
cmd/controller/main.go
cmd/node/main.go

These annotations will help the monitoring system to pull all the needed metrics. 
Also, this PR fixes typo in the metrics-path element

[ISSUE-228] Add annotations for the metrics discovery

---

api/v1/types.proto
pkg/base/k8s/cr_helper.go
pkg/common/ac_operations.go
pkg/crcontrollers/lvg/lvgcontroller.go
pkg/crcontrollers/lvg/lvgcontroller_test.go
pkg/node/volumemgr.go
pkg/node/volumemgr_test.go

* New field in LVG structure _Health_
* If drive health is changed, lvg health  and status are also changed

[ISSUE-88] Handle disk health change for lvg volumes

---

pkg/node/node.go
pkg/node/node_test.go

1) Uncomment logic with owner addition in NodePublish request
2) Make Owner slice nil during NodeUnpublish

[ISSUE-86] Handle owner addition/deletion during node publish/unpublish

---

Makefile
cmd/controller/main.go
cmd/node/main.go
pkg/metrics/metrics.go
variables.mk

Expose build parameters with ldflags and from constants

[ISSUE-249] Expose build info metrics 

---

pkg/base/k8s/kubeclient.go
pkg/metrics/common/kubeclient.go

Expose duration of kube-client methods

[ISSUE-251] Expose duration of kube-client methods

---

pkg/node/volumemgr.go

Caused by different case in `lsblk` and SN returned by `drive manager`:
```
Spec:
Serial Number:  64122B9F512A0010
root@baremetal-csi-node-9gq8p:/# lsblk -o NAME,SERIAL,VENDOR,MODEL
NAME                         SERIAL           VENDOR   MODEL
sdb                          64122b9f512a0010 ATA      DELLBOSS VD
```
Matching replaced by block device name to address issue with `loopbackmgr`.

[ISSUE-259] non zero ac for system disk

---

pkg/scheduler/patcher/main.py

Trace level in the python script will act like debug.

[ISSUE-265] Trace level cause crash in the extender

---

charts/baremetal-csi-plugin/Chart.yaml
charts/csibm-operator/Chart.yaml
charts/scheduler-extender/Chart.yaml
charts/scheduler/Chart.yaml
pkg/base/constants.go
test/app/nginx.yaml
variables.mk

Bump version to 0.0.13
Build done locally

[ISSUE-264] Change version to 0.0.13

---

.github/workflows/pr.yml
test/e2e/baremetal_e2e_test.go

Trigger PR validation in GH actions

[ISSUE-275] Add PR validation with GH actions

---

docs/proposals/caching.md

Initial version of caching proposal

[ISSUE-269] Caching proposal

---

docs/proposals/volume-expansion.md

Add proposal in docs for volume expansion

[ISSUE-268] Volume expansion proposal

---

pkg/base/linuxutils/fs/fs_helper.go
pkg/controller/controller.go
pkg/mocks/linuxutils/fs_helper.go
pkg/mocks/provisioners/fs_operations.go
pkg/node/node.go
pkg/node/node_test.go
pkg/node/provisioners/drive_provisioner.go
pkg/node/provisioners/lvm_provisioner.go
pkg/node/provisioners/utilwrappers/fs_operations.go
pkg/node/provisioners/utilwrappers/fs_operations_test.go
test/e2e/common/pod.go
test/e2e/scenarios/controller-node-fail.go
test/e2e/scenarios/different-sc-test.go
test/e2e/scenarios/drive-health-change.go
test/e2e/scenarios/node-reboot.go
test/sanity/sanity_test.go

Issue #292 
Add Support for RAW Block volumes

[ISSUE-292] RAW Block volumes support

---

pkg/base/capacityplanner/node_capacity.go

Split function logic to two separate functions:  first should provide AC selection for "full drive" storage classes, second for LVM based SC

[ISSUE-293] capacityplanner.selectACForVolume function refactoring

---

.github/workflows/pr.yml

The new version of golangci-lint and improved caching for modules and linter.
closes #289

[ISSUE-289] update golangci-lint version

---

docs/proposals/csi-deployment-crd.md

* Add proposal with CRD structure for CSI

[ISSUE-307] Prepare CRD for CSI deployment

---

Makefile.validation
pkg/mocks/linuxutils/lsblk.go
pkg/node/volumemgr.go
test/sanity/sanity_test.go

Use WrabLsblk mock object in sanity testing

[ISSUE-320] Fix sanity testing

---

test/e2e/scenarios/node-labels.go
test/e2e/scenarios/setup.go

Add test with Shrink and then extend
in progress

[ISSUE-322] Add e2e tests for deployment with node labels

---

api/v1/acreservationcrd/availablecapacityreservation_types.go
api/v1/availablecapacitycrd/availablecapacity_types.go
api/v1/drivecrd/drive_types.go
api/v1/lvgcrd/logicalvolumegroup_types.go
api/v1/nodecrd/node_types.go
api/v1/volumecrd/volume_types.go
charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_availablecapacities.yaml
charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_availablecapacityreservations.yaml
charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_drives.yaml
charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_logicalvolumegroups.yaml
charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_volumes.yaml
charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_nodes.yaml

* Add kubebuilder markers to generate columns with `make generate-api`

[ISSUE-342] Add kubebuilder markers for column generation

---

docs/node-removal.md

* Fix incorrect markup syntax in node removal doc

[ISSUE-353] Fix node removal docs

---

charts/csi-baremetal-scheduler-extender/values.yaml
docs/README.md

Update README to reflect current project status and installation procedure
Not relevant

[ISSUE-357] update csi docs to reflect current project status

---

charts/csi-baremetal-driver/templates/controller.yaml
charts/csi-baremetal-driver/values.yaml

Set gRPC timeout parameter to csi-provisioner
Deploy postgresql (deploying platform and scaleobject without error)
15s isn't enought
23s isn't enought
30s is enougth

[ISSUE-360] set grpc deadline for csi provisioner

---

charts/csi-baremetal-driver/Chart.yaml
charts/csi-baremetal-operator/Chart.yaml
charts/csi-baremetal-scheduler-extender/Chart.yaml
charts/csi-baremetal-scheduler/Chart.yaml
pkg/base/constants.go
variables.mk

Signed-off-by: Mikhail Borisov <mikhail.borisov@emc.com>
Update version to 0.2.0
No needed

[ISSUE-377] Update version to 0.2.0

---

charts/csi-baremetal-scheduler-extender/templates/patcher-configmap.yaml
charts/csi-baremetal-scheduler-extender/templates/patcher.yaml
charts/csi-baremetal-scheduler-extender/values.yaml
pkg/scheduler/patcher/main.py

RKE platform paths are different rather vanilla k8s.
Also, there is a bug with backup path, also fixed.
Was tested manually on RKE2  cluster, testing with CI job to find any regressions

[ISSUE-373] CSI support for rke2r1

---

charts/csi-baremetal-driver/templates/controller.yaml
charts/csi-baremetal-driver/templates/node.yaml
charts/csi-baremetal-operator/templates/csibm-controller.yaml
charts/csi-baremetal-scheduler-extender/templates/patcher.yaml
charts/csi-baremetal-scheduler-extender/templates/scheduler-extender.yaml
charts/csi-baremetal-scheduler/templates/scheduler.yaml

Ephemeral folder for crashdump
And label for the logging system to detect which release deployed

[ISSUE-382] Labels for the logging and crashdump folder

---

pkg/base/capacityplanner/mocks.go
pkg/base/capacityplanner/planner.go
pkg/base/capacityplanner/planner_test.go
pkg/scheduler/extender/extender.go

Don't reserve capacity on all nodes
Custom CI passed

[ISSUE-370] Reserve resources on requested nodes only

---

pkg/scheduler/extender/extender.go

Add volume existing check in extender

[ ISSUE-390] Extender creates acr after volumes has been already created

---

api/v1/lvgcrd/logicalvolumegroup_types.go
charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_logicalvolumegroups.yaml

Fix typo in column name
Not required

[ISSUE-397] Fix typo in LVGs CRD

---

Makefile.validation

[ISSUE-419] Change pull and tag centos image

---

charts/csi-baremetal-driver/Chart.yaml
charts/csi-baremetal-operator/Chart.yaml
charts/csi-baremetal-scheduler-extender/Chart.yaml
charts/csi-baremetal-scheduler/Chart.yaml
pkg/base/constants.go
variables.mk

[ISSUE-415] Update version to 0.2.2

---

pkg/crcontrollers/drive/drivecontroller.go

CSI must put `replacement: ready`  annotation on the volume during disk replacement to inform application Operator that PVC/PV can be removed.
Tested DR flow manually:
```
borism1@ubuntu:/workspace/csi-baremetal$ volumes
Namespace   Id                                         Size        Type   Health   OpStatus    CSIStatus   Usage      Location                               Node
mishoyama   pvc-e2b465dd-6677-42ec-a5b3-f10600e0cb9a   210763776   xfs    BAD      OPERATIVE   PUBLISHED   RELEASED   9edc2e2f-02ec-4cda-b6ef-c3e7ce26bb3b   5dfbb668-3397-403e-a09a-bc4957508c77
...
borism1@ubuntu:/workspace/csi-baremetal$ kubectl annotate drive 9edc2e2f-02ec-4cda-b6ef-c3e7ce26bb3b replacement=ready
drive.csi-baremetal.dell.com/9edc2e2f-02ec-4cda-b6ef-c3e7ce26bb3b annotated …
```

[ISSUE-420] Update volumes annotations on disk replacement

---

pkg/controller/node/statemonitor.go

False-positive linter issue in state monitor.
n/a

[ISSUE-439] Linter issue in statemonitor.go

---

.github/workflows/main.yml
docs/README.md

Create status badge for PR validation
n/a

[#442] Create status badge for PR validation

---

docs/fake-attach.md
pkg/eventing/eventing.go
pkg/node/node.go
pkg/node/node_test.go

Add event FakeAttachEnabled, FakeAttachDisabled. Generated in NodeStageVolume and NodeUnstageVolume.

[ISSUE-446] fake attach events

---

pkg/node/node.go

Signed-off-by: yurkov anton <yurkov-ant@yandex.ru>
Move type event to error for fake attach involved

[ISSUE-446] fix type of fake-attach event

---

docs/proposals/automated-node-removal.md

Automation of node removal procedure POC

[ISSUE-434] Automated node removal Proposal

---

.github/workflows/pr.yml
Makefile.validation
docs/README.md

- upload coverage.out to codecov
- add mark to readme
- remove charts linting (need to do it in csi-baremetal-operator repo)

[ISSUE-459] Integration with codecov.io

---

charts/csi-baremetal-driver/Chart.yaml
charts/csi-baremetal-operator/Chart.yaml
charts/csi-baremetal-scheduler-extender/Chart.yaml
charts/csi-baremetal-scheduler/Chart.yaml
pkg/base/constants.go
variables.mk

Signed-off-by: Mikhail Borisov <mikhail.borisov@emc.com>
Update version to 0.3.0
n/a

Update version to 0.3.0

---

.github/workflows/pr.yml
charts/csi-baremetal-driver/Chart.yaml
charts/csi-baremetal-operator/Chart.yaml
charts/csi-baremetal-scheduler-extender/Chart.yaml
charts/csi-baremetal-scheduler/Chart.yaml
pkg/base/constants.go
variables.mk

Set version 0.4.0

---

docs/README.md

Signed-off-by: safronovD <danil_safronov@dell.com>
Update README

[ISSUE-501]  Update README

---

docs/proposals/csi-webhook.md

Add validating webhook to avoid more then one CSI Deployment creation

[ISSUE-503] Validating webhook proposal

---

pkg/drivemgr/basemgr/Dockerfile.build
pkg/drivemgr/loopbackmgr/Dockerfile.build
pkg/node/Dockerfile-kernel-5.4.build
pkg/node/Dockerfile.build

- Update Ubuntu version to fix CVEs
- Remove bash packet to resolve CVE-2019-18276
In progress

[ISSUE-507] Update Ubuntu version to 21.04

---

test/e2e/common/deploy.go

Fix CI issue caused by parameter change
CI in progress

[ISSUE-500] Fix CI issue caused by parameter change

---

charts/csi-baremetal-driver/Chart.yaml
charts/csi-baremetal-operator/Chart.yaml
charts/csi-baremetal-scheduler-extender/Chart.yaml
charts/csi-baremetal-scheduler/Chart.yaml
pkg/base/constants.go
variables.mk

Bump CSI Operator version to 0.5.0

[ISSUE-526] Bump CSI version to 0.5.0

---

pkg/base/k8s/kubeclient.go

Add labels:
```
app: csi-baremetal
app.kubernetes.io/name: csi-baremetal
```

[ISSUE-533] Add app labels to custom resources

---

pkg/crcontrollers/drive/drivecontroller.go

Changed an event message to be more clear.

[ISSUE-536] Change event wording

---

docs/CODEOWNERS

[ISSUE-544] code owners added

---

.golangci.yml
pkg/crcontrollers/drive/drivecontroller.go

- Remove related AC after drive is REMOVED and OFFLINE
- Fix nil pointer in locateDiskLED after error
```
user@user-vm ~> k annotate drive 751e9e50-cc14-4940-b038-897c8c1f6113 health=bad
drive.csi-baremetal.dell.com/751e9e50-cc14-4940-b038-897c8c1f6113 annotated
user@user-vm ~> k annotate drive 751e9e50-cc14-4940-b038-897c8c1f6113 removal=ready
drive.csi-baremetal.dell.com/751e9e50-cc14-4940-b038-897c8c1f6113 annotated
user@user-vm ~> k annotate drive 751e9e50-cc14-4940-b038-897c8c1f6113 action=remove
drive.csi-baremetal.dell.com/751e9e50-cc14-4940-b038-897c8c1f6113 annotated
user@user-vm ~> kgo drives
NAME                                   SIZE          TYPE   HEALTH   STATUS   USAGE     SYSTEM   PATH       SERIAL NUMBER                      SLOT   NODE …
```

[ISSUE-558] Fix stucked AC after DR procedure

---

docs/CONTRIBUTING.md

Add rule: Merge commit title with  "[ISSUE-ID] <short description>"

[ISSUE-579] increase contribution guideline

---

pkg/base/constants.go
variables.mk

Start working on version 1.1.0
n/a

[ISSUE-606] Update CSI version to 1.1.0

---

docs/PULL_REQUEST_TEMPLATE.md

Checkbox to set `project`
Documentation - n/a

[ISSUE-620] PR template updated to use projects

---

.github/workflows/e2e.yml
docs/README.md

Run e2e test on master push. Add badge.
n/a

[ISSUE-626] e2e test on master

---

test/e2e/baremetal_e2e_test.go
test/e2e/common/deploy.go

Collect pods and events logs for every tests on it's own file.

[ISSUE-633] Collect logs for every tests suite

---

.github/workflows/e2e.yml

Add junit report, logs to artifacts
How it looks https://github.com/rkiselenko/csi-baremetal/runs/4518289541

[ISSUE-647] Upload artifacts to GH

---

docs/proposals/non-default-namespace-deployment.md

Prepared proposal for supporting CSI deployment in non default namespace at Openshift

[ISSUE-644] Support non default CSI deployment at Openshift platform

---

.github/workflows/e2e.yml

Make artifacts available in GH workflow
Fix on comment trigger git ref

[ISSUE-647] e2e test artifacts

---

.github/workflows/e2e.yml

Make artifacts available in GH workflow
Post the test results as comments
More information about the build in comments

[ISSUE-647] e2e workflow

---

docs/proposals/volume-health-monitoring.md

Providing design notes about supporting volume health feature using k8s volume health monitor mechanism

[ISSUE-677]: Proposal for CSI volume health feature support

---

.github/workflows/e2e.yml

Change zip action, fix trigger event

[ISSUE-647] fix event trigger, change zip action

---

.github/workflows/e2e.yml

If tests fail we need to post e2e results as artifacts event for failed tests.

[ISSUE-691] E2E test results

---

pkg/base/k8s/kubeclient.go
pkg/base/k8s/kubeclient_test.go
pkg/common/volume_operations.go
pkg/common/volume_operations_test.go
pkg/controller/controller_test.go

Add `release` label in addition to `app`
```
borism1@borism1-VirtualBox:/workspace/csi-baremetal> kubectl get volumes -l release=my-release
NAME                                       SIZE        STORAGE CLASS   HEALTH   CSI_STATUS   LOCATION                               NODE
pvc-0b7fe462-ae56-4f3a-825a-1eec063f42e1   105906176   HDD             GOOD     PUBLISHED    c0e80b86-e518-4add-af48-b621142f7adc   56f323f7-8ec7-49fc-9481-82c20f3f1938
pvc-267e5ca3-3cdd-4ffd-8d4a-3196d42a28c7   105906176   HDD             GOOD     PUBLISHED    a66ba14f-c339-4af8-82c1-c5366db5efea   1571b49f-089e-456e-8a50-cea24af722f5
pvc-2726b055-2ee9-4eaf-a11c-9a8981f876f0   105906176   HDD             GOOD     PUBLISHED    dd62ff42-6a2e-4a94-8570-cf9b9e56b2cc   fe019a59-8300-4129-bc48-3a233a3e24d2 …
```

[ISSUE-707] volume release label added

---

docs/proposals/disk-affinity.md

Adding the proposal for disk affinity/anti-affinity feature

[ISSUE-690] disk affinity proposal 

---

docs/proposals/disk-affinity.md

Adding the proposal for disk affinity/anti-affinity feature

[ISSUE-690]: disk affinity/antiaffinity proposal refactoring

---

docs/README.md

Cherry-pick changes from release-1.0 branch
n/a

[ISSUE-735] CSI GA project status

---

docs/README.md

Add badge with the Go Report
n/a

[ISSUE-740] Add badge with the Go Report

---

pkg/scheduler/extender/extender.go
pkg/scheduler/extender/extender_test.go

Wait for reservation to be confirmed,  continue on reading error,
return after reservation confirmed or wait context deadline

[ISSUE-745] Wait for reservation to be confirmed

---

pkg/scheduler/extender/extender.go
pkg/scheduler/extender/extender_test.go

Reverts dell/csi-baremetal#746

Revert "[ISSUE-745] Wait for reservation to be confirmed"

---

pkg/common/test_data.go
pkg/common/volume_operations.go
pkg/common/volume_operations_test.go

Commented tests must be uncomment and fixed 

[ISSUE-371] Recover volume operation tests

---

pkg/controller/Dockerfile
pkg/crcontrollers/node/Dockerfile
pkg/scheduler/extender/Dockerfile

Directly specifying UUIDs at dockerfiles for controller, node-controller components

[ISSUE-744]: CIS hardening support

---

cmd/drivemgr/loopbackmgr/main.go
cmd/node/main.go
cmd/scheduling/extender/main.go
pkg/crcontrollers/node/common/annotation.go
pkg/crcontrollers/node/common/annotation_test.go
pkg/scheduler/extender/extender.go
pkg/scheduler/extender/extender_test.go

- Fix for scheduler extender doesn't respect node labels
- Recover commented tests for scheduler
Testing in issue #761

[ISSUE-761] Scheduler respect labeled node

---

Makefile
go.sum
variables.mk

Bug fix for missing varibale KIND_BUILD_DIR
The result of E2E

[ISSUE-766] remove replace bugfix

---

devkit/Dockerfile
devkit/Makefile

Add install protobuf to devkit. To not install before each csi build.
Run build and unit tests.

[issue-782] add install protobuf to devkit

---

.github/.codecov.yaml

Update color limits to
- 70% - yellow
- 85% - green
https://codecov.io/gh/dell/csi-baremetal/commit/22dca0acef8f88560cbeb55d3d0c314264c3a8ce/graphs/sunburst.svg

[ISSUE-808] Set custom values for codecov badge color limits

---

api/v1/types.proto
docs/README.md
pkg/base/linuxutils/partitionhelper/partition_helper.go
pkg/base/linuxutils/partitionhelper/partitionhelper_test.go
pkg/base/util/volume_helper.go
pkg/common/volume_operations.go
pkg/common/volume_operations_test.go
pkg/mocks/linuxutils/partitionhelper.go
pkg/mocks/provisioners/fs_operations.go
pkg/node/common_test_data.go
pkg/node/node.go
pkg/node/node_test.go
pkg/node/provisioners/drive_provisioner.go
pkg/node/provisioners/drive_provisioner_test.go
pkg/node/provisioners/lvm_provisioner.go
pkg/node/provisioners/lvm_provisioner_test.go
pkg/node/provisioners/utilwrappers/fs_operations.go
pkg/node/provisioners/utilwrappers/fs_operations_test.go
pkg/node/provisioners/utilwrappers/partition_operations.go
pkg/node/provisioners/utilwrappers/parttiion_operations_test.go
pkg/scheduler/extender/extender.go
pkg/scheduler/extender/extender_test.go
tests/e2e/scenarios/bare-metal-testdriver.go
tests/e2e/scenarios/setup.go

Deprecate inline volumes feature. Use generic ephemeral volumes instead.
CI passed

[ISSUE-822] Deprecate inline volumes

---

pkg/node/Dockerfile.build

Need to use Ubuntu 18 image due to https://github.com/dell/csi-baremetal/issues/842
manually

[ISSUE-843] Use Ubuntu 18 as base image

---

.github/workflows/pr.yml
pkg/node/liveness_check_test.go

- Update codecov action
- Use tokenless upload
https://github.com/dell/csi-baremetal/runs/6473403557?check_suite_focus=true

[ISSUE-853] Tokenless codecov reporting

---

pkg/controller/Dockerfile.build
pkg/crcontrollers/node/Dockerfile
pkg/node/Dockerfile-kernel-5.4.build
pkg/node/Dockerfile.build
pkg/scheduler/extender/Dockerfile
pkg/scheduler/patcher/Dockerfile
pkg/scheduler/plugin/Dockerfile

Update alpine-base images tp 3.16

[ISSUE-868] Update alpine-base images to 3.16

---

devkit/Makefile

Signed-off-by: Olga Mogish <olga.mogish@dell.com>
Docker version in devkit is updated
Run container from opensuse/leap:latest locally and install actual docker version.

[ISSUE-882] Up docker version

---

pkg/common/test_data.go
pkg/common/volume_operations.go
pkg/common/volume_operations_test.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/mocks/volume_operations.go

Revert #894 due to LVG CRs removing problems

[ISSUE-893] Revert "Handle CRs updating errors in DeleteVolume (#894)"

---

pkg/base/k8s/kubeclient.go
pkg/base/k8s/kubeclient_test.go
pkg/common/volume_operations.go
pkg/node/volumemgr.go
pkg/testutils/testutils.go

Added retries on k8s operations.
No details

[ISSUE-754]: adding retries on k8s operations

---

pkg/node/node.go
pkg/node/node_test.go

Signed-off-by: safronovD <danil_safronov@dell.com>
Backport changes from the release branch
Check https://github.com/dell/csi-baremetal/pull/919

[ISSUE-918] Apply WBT options after node reboot

---

pkg/scheduler/extender/extender.go
pkg/scheduler/plugin/plugin.go
pkg/scheduler/util/scheduler_utils.go

Implement CSI Scheduler Plugin Filter Function

---

pkg/scheduler/patcher/main.py

Change Pods Max Reschedule Interval to 60s via scheduler extender patcher in k8s 1.24 and 1.25. This change only applies to rke2 platform.
On an Atlantic cluster whose k8s version is 1.24, with scheduler extender patch image including this change, the provision time of 1 pod with CSI-managed PVCs has been reduced to about 1min as expected and the total provsion time of multiple pods with CSI-managed PVCs has also been reduced a lot.
On another Atlantic cluster whose k8s version is 1.21, with scheduler extender patch image including this change, this parameter has not been added to kube-scheduler init parameter as expected.

[ISSUE-926] Change Pods Max Reschedule Interval in k8s 1.24 and 1.25

---

pkg/scheduler/patcher/main.py

Change Pods Max Reschedule Interval to 60s via scheduler extender patcher in k8s 1.24 and 1.25. This change only applies to rke2 platform.
On an Atlantic cluster whose k8s version is 1.24, with scheduler extender patch image including this change, the provision time of 1 pod with CSI-managed PVCs has been reduced to about 1min as expected and the total provsion time of multiple pods with CSI-managed PVCs has also been reduced a lot.
On another Atlantic cluster whose k8s version is 1.21, with scheduler extender patch image including this change, this parameter has not been added to kube-scheduler init parameter as expected.

[ISSUE-926] Change Pods Max Reschedule Interval in k8s 1.24 and 1.25 

---

pkg/crcontrollers/node/Dockerfile
pkg/drivemgr/basemgr/Dockerfile.build
pkg/drivemgr/loopbackmgr/Dockerfile.build
pkg/node/Dockerfile-kernel-5.4.build
pkg/node/Dockerfile.build
pkg/scheduler/extender/Dockerfile
pkg/scheduler/patcher/Dockerfile

To solve issue #940 .
Changes: upgrade base images versions to a fixed one.
See internal Jira ticket.

[ISSUE-940] Some vulnerabilities found in components reported by Black Duck

---

pkg/drivemgr/basemgr/Dockerfile.build

fix build failed #942 
backout basemgr base image
https://asd-ecs-jenkins.isus.emc.com/job/csi-custom-build/670/console

[ISSUE-942] fix build fail

---

pkg/drivemgr/basemgr/Dockerfile.build
pkg/drivemgr/loopbackmgr/Dockerfile.build
pkg/node/Dockerfile-kernel-5.4.build
pkg/node/Dockerfile.build

#940 
add upgrade steps to fix CVE.
basemgr testing:
https://asd-ecs-jenkins.isus.emc.com/job/csi-custom-acceptance/617/
short ci testing:
https://asd-ecs-jenkins.isus.emc.com/view/Atlantic/job/csi-custom-ci/1519/
halmgr testing:
https://asd-ecs-jenkins.isus.emc.com/job/csi-custom-acceptance-tar_a/213/

[ISSUE-940] Some vulnerabilities found in components

---

variables.mk

change version number to 1.2.0

change version number to 1.2.0 for OBS Epoch release

---

variables.mk

[ISSUE-982] Change version in master to 1.3.0

---

variables.mk

[ISSUE-984] add NOTICE

---

pkg/drivemgr/drivemgr-update-history.md

This is to change git commit history for drivemgr proprietary code. 

update drivemgr lib for proprietary code

---

api/v1/constants.go
pkg/base/capacityplanner/node_capacity.go
pkg/base/capacityplanner/node_capacity_test.go
pkg/base/capacityplanner/planner_test.go
pkg/crcontrollers/drive/drivecontroller.go
pkg/crcontrollers/drive/drivecontroller_test.go

[ISSUE-991]  disk taint-like mechanism

---

pkg/drivemgr/drivemgr-update-history.md

This is to change git commit history for drivemgr proprietary code.

introduce drivemgr lib updates

---

variables.mk

changer version number to 1.4.0.

[ISSUE-1038] 1.3.0 branched out. Change version to 1.4.0.

---

Makefile.validation
go.mod
go.sum

Add missing junit-report binary

[1059] Add missing junit-report binary

---

variables.mk

[Issue:1061] 1.5 version

---

.github/workflows/e2e.yml
devkit/Makefile
docs/CONTRIBUTING.md

Secondary scheduler upgrade
Full regression tests

[Issue-1049] fixing cves

---

variables.mk

[ISSUE-1068] Upgrade CSI sidecars

---

pkg/drivemgr/drivemgr-update-history.md

Do not alter serial disk number
All regression tests

[Issue: 1070] Remove upper case from serial number

---

pkg/scheduler/patcher/Dockerfile

Upgrade base image of the patcher component to latest version

[ISSUE-1071] Upgrade patcher base image

---

variables.mk

[ISSUE-1073] Upgrade grpc-heatlh-probe

---

pkg/base/linuxutils/fs/fs_helper.go

Increasing retries to check ConsistentRead to handle the inconsistent read issue during upgrade. 
Full automation tests

[Issue-1081] Extending ConsistentRead retries

---

variables.mk

[Issue-1091] 1.5.1 version

---

pkg/base/linuxutils/lsblk/lsblk.go
pkg/base/linuxutils/lsblk/lsblk_test.go
pkg/scheduler/extender/extender.go
variables.mk

Feature issue 1096

---

api/v1/drivecrd/drive_types.go

[ISSUE-1100] Remove SmartInfo from kubectl get drives output

---

pkg/base/linuxutils/lsblk/lsblk.go
pkg/base/linuxutils/lsblk/lsblk_test.go
pkg/mocks/commands.go

[issue-1114] Revert SerachDrivePath changes

---

Makefile

[ISSUE-1117] Adjust makefile to generate/clean smart API

---

pkg/scheduler/patcher/main.py

Updating kubescheduler config in patcher for 1.29

[ISSUE-1119] Updating kubescheduler config in patcher for 1.29

---

pkg/scheduler/patcher/Dockerfile

Upgrade to python:3.13.0a4-alpine3.19

[issue-1108] fixing CVEs

---

variables.mk

[ISSUE-1124] Set new release version v1.7.0 on master branch

---

pkg/node/volumemgr.go

[issue-1088] send correct status

---

pkg/controller/Dockerfile.build
pkg/crcontrollers/node/Dockerfile
pkg/scheduler/extender/Dockerfile
pkg/scheduler/plugin/Dockerfile

Fixing CVEs reported by scanning tool._
Full regression.

[ISSUE-1137] cves fixes

---

pkg/controller/Dockerfile.build
pkg/crcontrollers/node/Dockerfile
pkg/scheduler/extender/Dockerfile
pkg/scheduler/plugin/Dockerfile

Fixing CVEs reported by scanning tool._

[ISSUE-1137] CVE fixes - rel/cmo-8.0

---

cmd/node/main.go
pkg/node/volumemgr.go

Improved logging for creating and updating CRs.

[ISSUE-1143]: add logging for creating and updating CRs

---

.github/workflows/release.yml

[ISSUE-1150] rename jungwinter/split action

---

pkg/base/linuxutils/lsblk/lsblk.go
pkg/base/linuxutils/lsblk/lsblk_test.go

Used a serial number to compare drives.

[ISSUE-1145]: use a serial number to compare drives

---

pkg/mocks/drivemgr.go
pkg/node/smart.go
pkg/node/smart_test.go

Added JSON validation for Smart Info responses.

[ISSUE-1153]: JSON validation for smart-info

---

pkg/drivemgr/drivemgr-update-history.md

update drivemgr-update-history.md
N/A

CY2310 hal branch cut

---

pkg/crcontrollers/drive/drivecontroller_test.go

[ISSUE-1166] Disk Eject: Single volume scenario - LED locate failure

---

pkg/drivemgr/drivemgr-update-history.md

update hal manager CY2310

---

pkg/drivemgr/basemgr/Dockerfile.build
pkg/drivemgr/loopbackmgr/Dockerfile.build
pkg/node/Dockerfile-kernel-5.4.build
pkg/node/Dockerfile.build

[ISSUE-1164] cves fixes

---

pkg/crcontrollers/drive/drivecontroller.go
pkg/crcontrollers/drive/drivecontroller_test.go
pkg/node/node.go
pkg/node/node_test.go
pkg/node/volumemgr.go

Implemented the disk replacement procedure with the fake attachment.

[ISSUE-1159]: Disk Eject, disk replacement with fake-attach

---

pkg/drivemgr/basemgr/Dockerfile.build
pkg/drivemgr/loopbackmgr/Dockerfile.build
pkg/node/Dockerfile-kernel-5.4.build
pkg/node/Dockerfile.build

[ISSUE-1164] cvew fixes

---

tests/e2e-test-framework/.flake8
tests/e2e-test-framework/.pylintrc
tests/e2e-test-framework/README.md
tests/e2e-test-framework/conftest.py
tests/e2e-test-framework/framework/description_plugin.py
tests/e2e-test-framework/framework/kubernetes_helper.py
tests/e2e-test-framework/framework/propagating_thread.py
tests/e2e-test-framework/framework/qtest_helper.py
tests/e2e-test-framework/framework/sts.py
tests/e2e-test-framework/framework/utils.py
tests/e2e-test-framework/pytest.ini
tests/e2e-test-framework/requirements.txt
tests/e2e-test-framework/tests/test_sts_hdd.py
tests/e2e-test-framework/tests/test_sts_loopback.py
tests/e2e-test-framework/tox.ini

Feature issue 1171

---

docs/drive-replacement.md

[issue-1176] Failed volume workaround

---

pkg/node/volumemgr.go
pkg/node/volumemgr_test.go

issue-1174

---

tests/e2e-test-framework/framework/sts.py
tests/e2e-test-framework/tests/test_sts_hdd.py

Add mechanism to configure testing StatefulSet with multiple volumes

[Issue-1188]: add dynamic volume configuration of the testing StatefulSet

---

tests/e2e-test-framework/framework/ssh.py
tests/e2e-test-framework/framework/sts.py
tests/e2e-test-framework/requirements.txt

Added remote command executor through ssh, it'll simplify our e2e tests/

[ISSUE-1190]: remote command executor for e2e (ssh)

---

tests/e2e-test-framework/framework/const.py
tests/e2e-test-framework/framework/utils.py

Implement framework functions connecting with cleaning CSI resources, recreating pods, getting ips.

[ISSUE-1199]: cleaning resources, pod recreation

---

pkg/drivemgr/drivemgr-update-history.md

trigger halmgr build

---

tests/e2e-test-framework/conftest.py
tests/e2e-test-framework/framework/const.py
tests/e2e-test-framework/framework/utils.py
tests/e2e-test-framework/tests/test_fake_attach.py
tests/e2e-test-framework/tests/test_fake_attach_dr.py

E2E tests for multiple volume per pod with fake-attach scenario.

[ISSUE-1211]: working multiple volumes per pod with fake-attach

---

.github/workflows/e2e.yml
devkit/Makefile
go.mod
tests/go.mod

[issue-1220] cve fix

---

tests/kind/small-kind.yaml

Disable default CNI in kind config

[ISSUE-1195] disable default cni kind

---

pkg/scheduler/patcher/Dockerfile

Fixing CVEs critical/high, CSVV 7+
Regression

[ISSUE-1225] CVE reported for csi-baremetal-scheduler-patcher for I

---

pkg/drivemgr/drivemgr-update-history.md

Halmgr build trigger 7.6.2

---

pkg/base/linuxutils/fs/fs_helper.go

[issue-1240] space allocation

---

pkg/crcontrollers/drive/drivecontroller.go
pkg/node/volumemgr.go

[ISSUE-1246]: (CMO-10.0) increased retry count, improved logging

---

pkg/crcontrollers/drive/drivecontroller.go
pkg/node/volumemgr.go

[ISSUE-1246]: (CMO-9.0) increased retry count, improved logging

---

Makefile

Review and update the filter criteria for tests to be executed.

[issue-1254] update csi test filter

---

pkg/drivemgr/drivemgr-update-history.md

[issue-1258] cve fixes

---

pkg/base/linuxutils/fs/fs_helper.go

Fixing space allocation issue to allow space allocation until 1% left. 

[issue-1240] space allocation fix

---

variables.mk

[ISSUE-1260] update sidecars

---

variables.mk

Upgrading sidecars due to reported CVEs
Regression tests

[ISSUE-1260] Sidecar images updates

---

Makefile

[ATL-33499] improve e2e test results reporting

---

pkg/controller/identity_test.go

Increasing UT coverage for identity functionality
N/A

[ISSUE-658] identity UT

---

pkg/scheduler/patcher/requirements.txt

Fixing CVEs in the patcher component.
Regression tests.

[ISSUE-1267] patcher CVEs fixes
